apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  type: NodePort
  externalIPs: 
  - 10.0.2.15
  ports:
  - port: 9042
    name: db
    targetPort: 9042
  selector:
    app: cassandra